### ISSUE TITLE
contextmenu do not hide when action done

### ISSUE THREAD

**Issue by mckaygerhard** [JohnDoh/Roundcube-Plugin-Context-Menu#66]
when i made any action using the context menu this do not hide or dissapear when action done!

console do not show any error on browsers

i test in any browser, only work with lasted 30 and 31 of firefox.. using the kolab skin, i cant rigth cilck outside the menu and dissapear..

with oficial skin the menu do not hide in any case, i must reload to dissapear
only with kolab skin i can hide with an outside click

**Comment by mckaygerhard** [comment]
the commit db0dca4b3fe49c51911bb284b4d66eaac99bfd98 fixeds this when action are done
but still do not hide if no action are performed or/and made a click outside menu

**Comment by JohnDoh** [comment]
I'm going to close this ticket because I think whatever is wrong is actually linked to #65 and not a separate issue.

**Comment by mckaygerhard** [comment]
hello @JohnDoh this must be reopened.. i separate the issue due there two problems .. the other problem its that if i make a right click and then now i do nothing, menu does no go away! event i right click outside..

of course, the issue said "..do not hide when action done" and with commit db0dca4 are solved, the problem described above are still happening if action are not performed!

**Comment by mckaygerhard** [comment]
how stupid, bu happiness due the #73 its related to this problem and now its partially gone at least!

**Comment by JohnDoh** [comment]
#73 is about compatibility with other plugins. please try with all other plugins disabled. i cannot recreate the issue.

**Comment by mckaygerhard** [comment]
of course its what i mean, maybe not mentioned, but i have many plugins enabled including 3 of you..

i'll test tomorrow u plugin contextmenu with the complete list of my and report feedback
