### ISSUE TITLE
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by rahs** [JohnDoh/Roundcube-Plugin-Context-Menu#69]
Roundcube 1.1.1

Only first message on list shown

Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
s.extend.clean	@	jquery.min.js?s=1409305598:4
s.buildFragment	@	jquery.min.js?s=1409305598:4
s.fn.extend.domManip	@	jquery.min.js?s=1409305598:4
s.fn.extend.append	@	jquery.min.js?s=1409305598:3
init	@	contextmenu.js?s=1429340030:535
rcm_callbackmenu_init	@	contextmenu.js?s=1429340030:277
rcm_listmenu_init	@	contextmenu.js?s=1429340030:30
(anonymous function)	@	functions.js?s=1429340030:36
rcube_event_engine.triggerEvent	@	common.js?s=1426539290:379
init_message_row	@	app.js?s=1426539290:1976
(anonymous function)	@	app.js?s=1426539290:223
rcube_event_engine.triggerEvent	@	common.js?s=1426539290:379
rcube_list_widget.init_row	@	list.js?s=1426539290:192
rcube_list_widget.insert_row	@	list.js?s=1426539290:375
add_message_row	@	app.js?s=1426539290:2164
(anonymous function)	@	VM302:5
http_response	@	app.js?s=1426539290:7420
http_request.$.ajax.success	@	app.js?s=1426539290:7339
s.Callbacks.d	@	jquery.min.js?s=1409305598:2
s.Callbacks.v.fireWith	@	jquery.min.js?s=1409305598:2
S	@	jquery.min.js?s=1409305598:4
s.support.ajax.s.ajaxTransport.send.r	@	jquery.min.js?s=1409305598:4

**Comment by JohnDoh** [comment]
Did you install Roundcube from Debian packages? I ask because I have seen this error mentioned before when the Debian package is used because an incorrect version of jQuery is installed.

**Comment by rahs** [comment]
Yes, the original installation was from a repository. How to replace jQuery to the correct version?

Now installed
ii  libjs-jquery                   1.7.2+dfsg-3.2                all          JavaScript library for dynamic web applications
ii  libjs-jquery-mousewheel        10-2                          all          jQuery Mousewheel Plugin
ii  libjs-jquery-ui                1.10.1+dfsg-1                 all          JavaScript UI library for dynamic web applications

**Comment by JohnDoh** [comment]
i'm not sure. some comments in the bug report suggest just using the version shipped with Roundcube instead https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785333
