### ISSUE TITLE
Installation through composer fails

### ISSUE THREAD

**Issue by harriperhana** [JohnDoh/Roundcube-Plugin-Context-Menu#70]
I'm getting following error while trying to install this plugin:
Loading composer repositories with package information
Updating dependencies (including require-dev)
  [ErrorException]
  Undefined index: 1.1.0.0-beta
--
Here is my json:
{
    "name": "roundcube/roundcubemail",
    "description": "The Roundcube Webmail suite",
    "license": "GPL-3.0+",
    "repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net/"
        }
    ],
    "require": {
        "php": ">=5.3.7",
        "roundcube/plugin-installer": "~0.1.6",
        "johndoh/contextmenu": "dev-master"
    },
    "minimum-stability": "dev"
}
--
I have no idea what i'm doing wrong there...

**Comment by JohnDoh** [comment]
this is a known issue with the plugin-linstaller plugin from Roundcube. Please change the line `"roundcube/plugin-installer": "~0.1.6"` in the "require" section of your composer.json file to `"roundcube/plugin-installer": "*"` and that should sort out the problem.

**Comment by harriperhana** [comment]
Hello JohnDoh,

Thanks for the advice. I tried that trick but it didn't solve my issue, I still get the same "Undefined index: 1.1.0.0-beta" error. Any idea what to try next?
--
Here is my updated json:

{
    "name": "roundcube/roundcubemail",
    "description": "The Roundcube Webmail suite",
    "license": "GPL-3.0+",
    "repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net/"
        }
    ],
    "require": {
        "php": ">=5.3.7",
        "roundcube/plugin-installer": "*",
        "johndoh/contextmenu": "dev-master",
        "johndoh/globaladdressbook": "dev-master"
    },
    "minimum-stability": "dev"
}

**Comment by JohnDoh** [comment]
I thought that would sort it. I've seen reports from other people on the forum and trac that it does. There is not really anything else I can suggest, the problem is not caused by this plugin. You could try on the forum or the users mailinglist to see if any one else has any ideas.
