### ISSUE TITLE
Not working with newest RC Version 1.1.3

### ISSUE THREAD

**Issue by isikerkan** [JohnDoh/Roundcube-Plugin-Context-Menu#71]
Hello,

I've upgraded my Roundcube to version 1.1.3. Strangly the Context Menu is not working anymore. I tryed the version from the composer and also the one on github.

I've read in the Changelog of Roundcube, that they have updated TinyMCE to the newest version.

Maybe this is a incompatibility. I've already checked all the permissions and found no issues on them. Also checked if an other plugins is blocking the context menu, but everything was alright.

My System:

Debian Sid (experimental)
Roundcube 1.1.3
MySQL 5.6
PHP 5.5/5.6
Java 8

**Comment by JohnDoh** [comment]
What exactly is the problem?

**Comment by isikerkan** [comment]
The context menu is not appearing when you right click. Just the usual one from your webbrowser.

**Comment by JohnDoh** [comment]
Works for me. Double check the plugin is actually enabled and check for errors in your browser's JS console.
