### ISSUE TITLE
Empty trash link

### ISSUE THREAD

**Issue by dapphp** [JohnDoh/Roundcube-Plugin-Context-Menu#76]
In dev-release-2.1 and in the current Git master branch, there is an issue (tested with Roundcube 1.1.4) where the "Empty Trash" link is not enabled unless you first left-click the Trash folder to select it, and then right click to activate the context menu.

**Steps to reproduce:**
Select any folder except trash
Right click on the Trash folder (without selecting it first)
"Empty Trash" is disabled and cannot be clicked

**Expected Behaviour:**
We also run Roundcube 0.9.5 - with this version when you right-click on Trash the Empty Trash link is enabled regardless of what folder is selected.

**Comment by dapphp** [comment]
I think I was able to resolve the issue in RC 1.1.4.

I've created this [patch](https://github.com/JohnDoh/Roundcube-Plugin-Context-Menu/files/198707/patch.txt) which checks to see if the context menu target folder is the Trash folder and if so it forces Roundcube to open that folder (so the rcmail.env.mailbox is set appropriately).

Previously I'd tried to just set that env value if it didn't match the context menu target but upon emptying the folder, it worked correctly but caused the message list for the selected folder to disappear which made it look like the wrong folder was purged.  The trash was actually emptied and not the selected folder but it made it look like the wrong folder was purged.

Rather than trying to get all the appropriate variables set to correct that, it seemed easiest to just select the Trash folder when it is right clicked on and the context menu is activated.

Merge at your own risk - I've tested this but it may need further testing.

**Comment by JohnDoh** [comment]
Between 0.9 and now there have been a lot of changes in both the Roundcube core and this plugin. One of the biggest changes was in this plugin was the fact it has been rewritten to work much closer with the Roundcube UI and do much less hacks to get functionality in. One downside of this is the Empty and Compact functions on the folder menu which now only work for the folder you are in.

Your suggestion of loading the folder when the menu is opened, I do not like. I do think that loading the folder on right click is expected behaviour.

One option might be to check the folder status when the menu is opened to see if can be emptied or compacted but that might slow down loading the menu.

**Comment by dapphp** [comment]
That's what the patch does - when you right click on the Trash folder and the context menu is initialized, if the folder is the trash folder, it loads that folder.

Given that empty now only works on the folder you are in, whether or not this is desirable, it seems to be the only way?

We just have many users who are accustomed to being able to right click > empty trash without the message list changing, so it'll be an adjustment, but if it's the way it has to be then it's the way it has to be :)

**Comment by JohnDoh** [comment]
i don't agree with that. Why make the usability worse for such small benifits. Also surely most of the time wouldnt someone want to go and see what is in the folder before they empty it?

In any case try this patch https://gist.github.com/JohnDoh/bb4fdb62ce927ef66ea83f51fe04a76f (Note it has not been fully tested). It does what you want without the need to change folders

**Comment by dapphp** [comment]
Thank you for the patch.  I was just trying to make it work with minimal time investment and little knowledge about much of the Roundcude UI code.  I'll try it on Monday when I'm back at work.  I appreciate the time, I wasn't sure whether or not you were currently keeping up on this project so thank you very much for the code and your time.

Feel free to close this now if you'd like as I don't believe there is much more to be added to the conversation unless you want to keep it open to resolve for a future release of the plugin.

**Comment by JohnDoh** [comment]
Did you have a chance to test the patch? I'm interested if you found any problems with it.

**Comment by dapphp** [comment]
So far so good.  Tried it in a few browsers and it works great so far.  Only thing, if the Trash has unread items, it successfully empties but does not clear the message count label from the folder so initially people may be unsure if it really emptied (despite the success message saying it did).

We are going to release Roundcube updates to (tens?) of thousands of customers this weekend so if there is anything else, we should get good feedback.

Thank you!

**Comment by smares** [comment]
I just noticed that with version 3 of this plugin and Roundcube 1.4.0 running the Elastic skin, the Empty command is greyed out sometimes, probably if the right-clicked folder was filled outside of the Roundcube context (e.g. using a mail client on the computer or phone) so Roundcube doesn't know the folder is no longer empty.
