### ISSUE TITLE
[Exception]  Version check failed!

### ISSUE THREAD

**Issue by xdexter** [JohnDoh/Roundcube-Plugin-Context-Menu#80]
Hello,

I'm trying install plugin through composer, my composer.json is:

{
    "name": "roundcube/roundcubemail",
    "description": "The Roundcube Webmail suite",
    "license": "GPL-3.0+",
    "repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net/"
        }
    ],
    "require": {
        "php": ">=5.3.7",
        "roundcube/plugin-installer": "~0.1.6",
        "johndoh/contextmenu": "dev-master"
    },
    "minimum-stability": "dev"
}

When i run 'composer install' i have this error:
  [Exception]                                                                                               
  Version check failed! johndoh/contextmenu requires Roundcube version >= 1.3.999.0, 1.2.3.0 was detected.

Someone can help me please?

**Comment by rmcaninch** [comment]
You either need to update Roundcube to 1.3 or more likely change your composer line from dev-master to a previous version of the plugin. 

Unless you're developing you probably don't want to use any Git master branches.

**Comment by JohnDoh** [comment]
@rmcaninch is right. the git-master version of contextmenu currently requires the git-master version of Roundcube as it has been updated for changes in the core.

**Comment by xdexter** [comment]
Perfect, thanky everyone.

**Comment by leonvzGit** [comment]
@xdexter, Care to share the version string you used ?
