### ISSUE TITLE
Hook to plugins.roundcube.net not working?

### ISSUE THREAD

**Issue by dapphp** [JohnDoh/Roundcube-Plugin-Context-Menu#81]
Thanks for the super fast update on this plugin.  I'm unable to get it to update from composer though because it looks like plugins.roundcube.net is still pointing dev-master at edf9303 (remove @version @package_version@) and doesn't have release-2.2.

No big deal as I just downloaded the release and manually installed, but this might save others some time and head scratching and allow our automated deployment to work going forward.

**Comment by JohnDoh** [comment]
Thanks. I logged in and triggered a manual update. I thought it was meant to update automatically.
