### ISSUE TITLE
Intended behaviour for contextmenu selection

### ISSUE THREAD

**Issue by alecpl** [JohnDoh/Roundcube-Plugin-Context-Menu#88]
What is intended for a case when one message is selected on the list and user right-clicks another message. Should the action taken be on two messages or only the one right-clicked? Or maybe the selected previously message should be de-selected as e.g. Thunderbird does? Another case, two messages are selected and user right-clicks one of them.

**Comment by JohnDoh** [comment]
- No message selected, right click on a message: that single message is the target
- 1 or more messages selected, right click on another (not selected message): that single message is the target
- 1 or more messages selected, right click on one of the selected messages: all the selected messages are the target

This is the same behaviour I have seen in desktop applications e.g. Outlook

**Comment by alecpl** [comment]
As I said Thunderbird selects the right-clicked message unselecting others, but I can live with what you implemented. Thanks.
