### ISSUE TITLE
"Archive" icon

### ISSUE THREAD

**Issue by alecpl** [JohnDoh/Roundcube-Plugin-Context-Menu#89]
When the 'archive' plugin is enabled context menu on the messages list contains "Archive" entry that has no icon.

There's no archive-specific icon in the Move to.../Copy to... folders list, so we might need to fix that in the archive plugin first. Then you'd just re-use an existing icon.

**Comment by JohnDoh** [comment]
I prefer to leave contextmenu icons for other plugins to the plugin's developer. For an example if you take a look at my markasjunk2 plugin you'll see how it defines icons for the contextmenu plugin in the skin CSS.

I supose an exception could be made for plugins that are distributed with Roundcube but images are not my strongest thing.

Note: This is skin dependant and the way things are defined in the CSS - with the new Elastic skin and Fontawesome this issue does not exist.

**Comment by JohnDoh** [comment]
these are the icons which could be added for plugins distributed with rc::

- archive - on message toolbar
- managesieve - in message menu, icon exists in Larry but not Classic
- markasjunk - on message toolbar
- vcard_attachments - on compose screen, already done
